#!/usr/bin/env python3
"""Generate docs/nvsh-import-provenance.md from the NVSH_PROVENANCE headers.

Every jev_factory module cited from nvsh carries a module-level
``NVSH_PROVENANCE`` dict (see docs/provenance.md). This reads them with
``ast`` (never imports a module), and writes one table of every imported
module plus each module's adaptations.

Usage:
    gen-provenance-doc.py           # rewrite the doc
    gen-provenance-doc.py --check   # exit 1 if the committed doc is stale
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "jev_factory"
DOC = ROOT / "docs" / "nvsh-import-provenance.md"
NAME = "NVSH_PROVENANCE"

HEADER = """\
# nvsh import provenance

Generated by `scripts/gen-provenance-doc.py` from the module-level
`NVSH_PROVENANCE` headers in `jev_factory/` (the convention is in
[provenance.md](provenance.md)). Do not edit it by hand: change a header and
regenerate, because `tests/test_provenance_doc.py` fails when this file is stale.

Each module below was cited (copied and adapted) from
[nvsh](https://github.com/agentculture/nvsh) at commit `{commit}`, under its
`{licence}` licence. The `nvsh path` column is relative to the nvsh repo; the
adaptations list what changed on the way in.

{count} modules.
"""


def provenance(path: Path):
    """The literal NVSH_PROVENANCE of *path*, or ``None`` when it has none."""
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if isinstance(node, ast.Assign):
            targets, value = node.targets, node.value
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            targets, value = [node.target], node.value
        else:
            continue
        if any(isinstance(t, ast.Name) and t.id == NAME for t in targets):
            return ast.literal_eval(value)
    return None


def collect(pkg: Path = PKG) -> list[tuple[str, dict]]:
    """``[(repo-relative module path, provenance)]`` sorted by path."""
    found = []
    for path in sorted(pkg.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        value = provenance(path)
        if value is not None:
            found.append((path.relative_to(pkg.parent).as_posix(), value))
    return found


def render(entries: list[tuple[str, dict]]) -> str:
    commits = sorted({v["commit"] for _, v in entries})
    licences = sorted({v["licence"] for _, v in entries})
    out = [
        HEADER.format(commit=", ".join(commits), licence=", ".join(licences), count=len(entries))
    ]
    out += ["## Index", "", "| jev_factory module | nvsh path | commit | licence |"]
    out.append("|---|---|---|---|")
    for module, value in entries:
        out.append(
            f"| `{module}` | `{value['upstream']}` | `{value['commit']}` | {value['licence']} |"
        )
    out += ["", "## Adaptations"]
    for module, value in entries:
        out += ["", f"### `{module}`", ""]
        out.append(f"From `{value['upstream']}` at `{value['commit']}` ({value['licence']}).")
        out.append("")
        # A fenced block keeps identifiers such as `_x_y` and `<pid>` from being read as markdown.
        out += ["```text"] + [f"- {item}" for item in value["adaptations"]] + ["```"]
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    text = render(collect())
    if argv == ["--check"]:
        if not DOC.is_file() or DOC.read_text(encoding="utf-8") != text:
            print(f"{DOC.name} is stale: run scripts/gen-provenance-doc.py")
            return 1
        return 0
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
